<a href="https://colab.research.google.com/github/shivamkachhadiya/Python_For_Finance_Trading/blob/main/stock_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [144]:
import yfinance as yf
import numpy as np
import pandas as pd

In [145]:
price_data=[[100,200,500,600],[100,200,500,600],[100,200,500,600],[100,200,500,600]]
pd.DataFrame(price_data)

     0    1    2    3
0  100  200  500  600
1  100  200  500  600
2  100  200  500  600
3  100  200  500  600

In [146]:
price_data={"Name":["Apple","MSFT","TSLA","META"],
            "open":[100,200,500,600],
            "high":[100,200,500,600],
            "low":[100,200,500,600],
           "close":[100,200,500,600]}
dict_df=pd.DataFrame(price_data)
dict_df.set_index("Name",inplace=True)
dict_df

       open  high  low  close
Name
Apple   100   100  100    100
MSFT    200   200  200    200
TSLA    500   500  500    500
META    600   600  600    600

In [147]:
funda_df=pd.read_csv("fundamental_research_dataset_large.csv")
funda_df

,Ticker,Company Name,Sector,Industry,Market Cap (B),EPS,P/E Ratio,Dividend Yield (%),P/B Ratio,D/E Ratio
0,V,Visa Inc.,Utilities,Hardware,254.02,5.70,44.13,8.74,17.12,0.78
1,AMZN,"Amazon.com, Inc.",Healthcare,Beverages,299.46,1.98,49.14,2.21,17.88,0.88
2,PG,Procter & Gamble Co.,Services,Hardware,17.66,-5.98,31.60,1.58,10.19,2.00
3,TSLA,"Tesla, Inc.",Utilities,Hardware,182.48,1.80,17.33,0.62,14.84,1.23
4,V,Visa Inc.,Utilities,Beverages,366.58,-1.85,16.68,8.23,7.01,0.66
...,...,...,...,...,...,...,...,...,...,...
1045,JNJ,Johnson & Johnson,Services,Gas Utilities,267.98,-4.35,49.89,5.66,2.44,NaN
1046,GOOGL,Alphabet Inc.,Healthcare,Medical Devices,73.05,-4.04,29.94,5.04,13.90,2.57
1047,V,Visa Inc.,Consumer Goods,Hardware,392.21,-4.44,18.89,0.14,4.35,1.33
1048,GOOGL,Alphabet Inc.,Technology,Medical Devices,210.28,5.43,16.06,3.63,14.62,0.29
1049,GOOGL,Alphabet Inc.,Industrial Goods,Food Products,250.54,3.04,40.44,6.01,14.41,0.10

In [148]:
algo_df=pd.read_csv("algotrading_combined_dataset.csv")
algo_df

,Date,Ticker,Open,High,Low,Close,Volume
0,2018-04-19,MSFT,135.020393,136.388872,134.287813,134.958879,567659.7
1,2019-12-18,TSLA,157.398137,158.172379,155.502975,158.379035,814588.8
2,2019-05-02,GOOGL,132.461289,133.491003,131.001162,132.412955,75821.8
3,2019-03-14,BTC/USD,118.663604,119.486898,117.825819,117.351030,186962.1
4,2021-04-13,AMZN,177.919316,180.849308,175.373581,176.438086,624913.1
...,...,...,...,...,...,...,...
32865,2015-02-03,GOOGL,117.022229,119.022870,114.277587,117.436351,812259.0
32866,2017-02-17,AMZN,129.662516,130.296426,128.376515,127.824866,791293.5
32867,2024-05-23,AAPL,170.606324,171.900767,168.220234,169.031925,440209.9
32868,2020-05-08,AAPL,137.925964,140.663476,137.103445,137.479243,507224.7
32869,2024-07-16,AMZN,96.949110,99.434607,94.512888,96.694106,263393.8

In [149]:
#ROW COLUMNS
print(algo_df.shape)
print(funda_df.shape)

(32870, 7)
(1050, 10)

In [150]:
algo_df.dtypes

Date       object
Ticker     object
Open      float64
High      float64
Low       float64
Close     float64
Volume    float64
dtype: object

In [151]:
funda_df.dtypes

Ticker                 object
Company Name           object
Sector                 object
Industry               object
Market Cap (B)        float64
EPS                   float64
P/E Ratio             float64
Dividend Yield (%)    float64
P/B Ratio             float64
D/E Ratio             float64
dtype: object

In [152]:
algo_df.columns

Index(['Date', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [153]:
funda_df.columns

Index(['Ticker', 'Company Name', 'Sector', 'Industry', 'Market Cap (B)', 'EPS',
       'P/E Ratio', 'Dividend Yield (%)', 'P/B Ratio', 'D/E Ratio'],
      dtype='object')

In [154]:
algo_df.head()

,Date,Ticker,Open,High,Low,Close,Volume
0,2018-04-19,MSFT,135.020393,136.388872,134.287813,134.958879,567659.7
1,2019-12-18,TSLA,157.398137,158.172379,155.502975,158.379035,814588.8
2,2019-05-02,GOOGL,132.461289,133.491003,131.001162,132.412955,75821.8
3,2019-03-14,BTC/USD,118.663604,119.486898,117.825819,117.351030,186962.1
4,2021-04-13,AMZN,177.919316,180.849308,175.373581,176.438086,624913.1

In [155]:
algo_df.tail()

,Date,Ticker,Open,High,Low,Close,Volume
32865,2015-02-03,GOOGL,117.022229,119.022870,114.277587,117.436351,812259.0
32866,2017-02-17,AMZN,129.662516,130.296426,128.376515,127.824866,791293.5
32867,2024-05-23,AAPL,170.606324,171.900767,168.220234,169.031925,440209.9
32868,2020-05-08,AAPL,137.925964,140.663476,137.103445,137.479243,507224.7
32869,2024-07-16,AMZN,96.949110,99.434607,94.512888,96.694106,263393.8

In [156]:
algo_df.tail(20)

,Date,Ticker,Open,High,Low,Close,Volume
32850,2015-12-31,BTC/USD,158.252013,158.965126,155.404490,160.099985,271913.8
32851,2022-09-20,MSFT,183.605158,185.231169,181.537636,184.530775,676289.4
32852,2020-02-13,LTC/USD,95.549452,97.344053,95.030318,95.578946,674383.6
32853,2018-09-04,ETH/USD,150.565073,152.002930,149.948883,148.765314,70233.1
32854,2022-02-01,BTC/USD,169.994478,172.463267,169.064601,171.320991,496823.9
32855,2022-10-25,GOOGL,130.873210,133.036421,130.345409,129.297192,624990.0
32856,2019-07-23,AMZN,128.889408,130.802963,127.092029,127.231740,556063.1
32857,2016-04-13,LTC/USD,93.552820,95.580681,92.358689,94.033031,61494.5
32858,2018-01-30,ETH/USD,143.867749,146.276254,142.903316,144.281367,853122.2
32859,2024-05-06,BTC/USD,155.593822,157.613675,154.088470,156.821140,267082.6
32860,2018-09-21,LTC/USD,171.443404,172.500267,170.538441,171.930710,570483.9
32861,2019-03-13,TSLA,99.496706,101.012064,97.525276,100.955262,302803.3
32862,2018-08-09,GOOGL,135.832878,136.673267,135.139594,134.989793,530183.2
32863,2018-06-18,BTC/USD,118.329531,121.007741,117.203544,117.698569,456599.3
32864,2019-11-12,BTC/USD,112.756618,113.803124,112.031189,112.514808,863022.8
32865,2015-02-03,GOOGL,117.022229,119.022870,114.277587,117.436351,812259.0
32866,2017-02-17,AMZN,129.662516,130.296426,128.376515,127.824866,791293.5
32867,2024-05-23,AAPL,170.606324,171.900767,168.220234,169.031925,440209.9
32868,2020-05-08,AAPL,137.925964,140.663476,137.103445,137.479243,507224.7
32869,2024-07-16,AMZN,96.949110,99.434607,94.512888,96.694106,263393.8

In [157]:
algo_df.sample(5)

,Date,Ticker,Open,High,Low,Close,Volume
23187,2018-11-12,TSLA,104.223583,105.016924,102.111149,104.703482,746851.2
25091,2017-07-21,ETH/USD,139.372162,140.431806,137.481989,140.983184,480201.4
3088,2021-10-11,TSLA,138.873211,141.846687,136.206669,138.348821,598253.2
28325,2020-02-13,ETH/USD,NaN,169.095708,163.869106,NaN,331434.4
12953,2015-08-21,MSFT,198.413436,199.778663,195.707887,199.336579,57402.9

In [158]:
algo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32870 entries, 0 to 32869
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    32870 non-null  object
 1   Ticker  32870 non-null  object
 2   Open    31877 non-null  float64
 3   High    32870 non-null  float64
 4   Low     32870 non-null  float64
 5   Close   31886 non-null  float64
 6   Volume  31886 non-null  float64
dtypes: float64(5), object(2)
memory usage: 1.8+ MB

In [159]:
funda_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1050 entries, 0 to 1049
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Ticker              1050 non-null   object
 1   Company Name        1050 non-null   object
 2   Sector              1050 non-null   object
 3   Industry            1050 non-null   object
 4   Market Cap (B)      1050 non-null   float64
 5   EPS                 1050 non-null   float64
 6   P/E Ratio           1050 non-null   float64
 7   Dividend Yield (%)  1050 non-null   float64
 8   P/B Ratio           1050 non-null   float64
 9   D/E Ratio           947 non-null    float64
dtypes: float64(6), object(4)
memory usage: 82.2+ KB

In [160]:
algo_df.describe()

               Open          High           Low         Close        Volume
count  31877.000000  32870.000000  32870.000000  31886.000000   31886.00000
mean     145.193810    146.994177    143.498415    145.298690  472621.43277
std       31.827694     31.830440     31.826154     31.872493  245694.22653
min       90.005229     90.596421     87.056671     88.084221   50074.00000
25%      117.762534    119.498864    116.113499    117.830927  259748.75000
50%      145.013326    146.816032    143.329086    145.137462  470539.85000
75%      173.093648    174.861680    171.435521    173.172288  685907.15000
max      199.988455    202.940489    199.313232    201.898956  899966.00000

In [161]:
algo_df.isnull().sum()

Date        0
Ticker      0
Open      993
High        0
Low         0
Close     984
Volume    984
dtype: int64

In [162]:
funda_df.isnull().sum()

Ticker                  0
Company Name            0
Sector                  0
Industry                0
Market Cap (B)          0
EPS                     0
P/E Ratio               0
Dividend Yield (%)      0
P/B Ratio               0
D/E Ratio             103
dtype: int64

In [163]:
algo_df.duplicated().sum()

np.int64(0)

In [164]:
funda_df.duplicated().sum()

np.int64(0)

In [165]:
algo_df.columns

Index(['Date', 'Ticker', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [166]:
algo_df.sum()

Date      2018-04-192019-12-182019-05-022019-03-142021-0...
Ticker    MSFTTSLAGOOGLBTC/USDAMZNMSFTLTC/USDBTC/USDETH/...
Open                                         4628343.084368
High                                         4831698.603849
Low                                           4716792.89322
Close                                        4632994.037125
Volume                                   15070007005.299999
dtype: object

In [167]:
funda_df.sum()

Ticker                VAMZNPGTSLAVUNHMSFTVPGTSLAAMZNPGPGMSFTJNJTSLAG...
Company Name          Visa Inc.Amazon.com, Inc.Procter & Gamble Co.T...
Sector                UtilitiesHealthcareServicesUtilitiesUtilitiesC...
Industry              HardwareBeveragesHardwareHardwareBeveragesCons...
Market Cap (B)                                                267970.41
EPS                                                               59.15
P/E Ratio                                                      33808.28
Dividend Yield (%)                                              5084.93
P/B Ratio                                                      11157.73
D/E Ratio                                                       1500.09
dtype: object

In [168]:
algo_df["High"].mean()

np.float64(146.99417717823778)

In [169]:
algo_df["Close"]

0        134.958879
1        158.379035
2        132.412955
3        117.351030
4        176.438086
            ...
32865    117.436351
32866    127.824866
32867    169.031925
32868    137.479243
32869     96.694106
Name: Close, Length: 32870, dtype: float64

In [170]:
algo_df["High"]

0        136.388872
1        158.172379
2        133.491003
3        119.486898
4        180.849308
            ...
32865    119.022870
32866    130.296426
32867    171.900767
32868    140.663476
32869     99.434607
Name: High, Length: 32870, dtype: float64

In [171]:
#selected cols
funda_df[["Ticker","Sector"]]

     Ticker            Sector
0         V         Utilities
1      AMZN        Healthcare
2        PG          Services
3      TSLA         Utilities
4         V         Utilities
...     ...               ...
1045    JNJ          Services
1046  GOOGL        Healthcare
1047      V    Consumer Goods
1048  GOOGL        Technology
1049  GOOGL  Industrial Goods

[1050 rows x 2 columns]

In [172]:
#select rows
algo_df.iloc[0]

Date      2018-04-19
Ticker          MSFT
Open      135.020393
High      136.388872
Low       134.287813
Close     134.958879
Volume      567659.7
Name: 0, dtype: object

In [173]:
#multiple rows
algo_df.iloc[0:5]

,Date,Ticker,Open,High,Low,Close,Volume
0,2018-04-19,MSFT,135.020393,136.388872,134.287813,134.958879,567659.7
1,2019-12-18,TSLA,157.398137,158.172379,155.502975,158.379035,814588.8
2,2019-05-02,GOOGL,132.461289,133.491003,131.001162,132.412955,75821.8
3,2019-03-14,BTC/USD,118.663604,119.486898,117.825819,117.351030,186962.1
4,2021-04-13,AMZN,177.919316,180.849308,175.373581,176.438086,624913.1

In [174]:
algo_df.iloc[0:10]

,Date,Ticker,Open,High,Low,Close,Volume
0,2018-04-19,MSFT,135.020393,136.388872,134.287813,134.958879,567659.7
1,2019-12-18,TSLA,157.398137,158.172379,155.502975,158.379035,814588.8
2,2019-05-02,GOOGL,132.461289,133.491003,131.001162,132.412955,75821.8
3,2019-03-14,BTC/USD,118.663604,119.486898,117.825819,117.351030,186962.1
4,2021-04-13,AMZN,177.919316,180.849308,175.373581,176.438086,624913.1
5,2023-04-26,MSFT,NaN,125.802870,120.427881,121.989629,802060.2
6,2016-10-14,LTC/USD,109.805147,111.867516,108.043710,109.663497,59191.6
7,2019-10-01,BTC/USD,132.723638,133.850036,131.748767,132.699536,130314.9
8,2016-04-07,ETH/USD,104.483139,105.418854,102.934351,104.443116,511973.8
9,2020-09-07,GOOGL,165.943668,168.548561,165.362393,166.351139,466373.1

In [176]:
funda_df.iloc[0:5,0:4]

  Ticker          Company Name      Sector   Industry
0      V             Visa Inc.   Utilities   Hardware
1   AMZN      Amazon.com, Inc.  Healthcare  Beverages
2     PG  Procter & Gamble Co.    Services   Hardware
3   TSLA           Tesla, Inc.   Utilities   Hardware
4      V             Visa Inc.   Utilities  Beverages

In [177]:
algo_df["NEW_COL"]="keeep"

In [178]:
algo_df

,Date,Ticker,Open,High,Low,Close,Volume,NEW_COL
0,2018-04-19,MSFT,135.020393,136.388872,134.287813,134.958879,567659.7,keeep
1,2019-12-18,TSLA,157.398137,158.172379,155.502975,158.379035,814588.8,keeep
2,2019-05-02,GOOGL,132.461289,133.491003,131.001162,132.412955,75821.8,keeep
3,2019-03-14,BTC/USD,118.663604,119.486898,117.825819,117.351030,186962.1,keeep
4,2021-04-13,AMZN,177.919316,180.849308,175.373581,176.438086,624913.1,keeep
...,...,...,...,...,...,...,...,...
32865,2015-02-03,GOOGL,117.022229,119.022870,114.277587,117.436351,812259.0,keeep
32866,2017-02-17,AMZN,129.662516,130.296426,128.376515,127.824866,791293.5,keeep
32867,2024-05-23,AAPL,170.606324,171.900767,168.220234,169.031925,440209.9,keeep
32868,2020-05-08,AAPL,137.925964,140.663476,137.103445,137.479243,507224.7,keeep
32869,2024-07-16,AMZN,96.949110,99.434607,94.512888,96.694106,263393.8,keeep

In [179]:
algo_df["NEW CLOSE"]=algo_df["Close"]*2

In [180]:
algo_df

,Date,Ticker,Open,High,Low,Close,Volume,NEW_COL,NEW CLOSE
0,2018-04-19,MSFT,135.020393,136.388872,134.287813,134.958879,567659.7,keeep,269.917759
1,2019-12-18,TSLA,157.398137,158.172379,155.502975,158.379035,814588.8,keeep,316.758069
2,2019-05-02,GOOGL,132.461289,133.491003,131.001162,132.412955,75821.8,keeep,264.825911
3,2019-03-14,BTC/USD,118.663604,119.486898,117.825819,117.351030,186962.1,keeep,234.702060
4,2021-04-13,AMZN,177.919316,180.849308,175.373581,176.438086,624913.1,keeep,352.876171
...,...,...,...,...,...,...,...,...,...
32865,2015-02-03,GOOGL,117.022229,119.022870,114.277587,117.436351,812259.0,keeep,234.872701
32866,2017-02-17,AMZN,129.662516,130.296426,128.376515,127.824866,791293.5,keeep,255.649733
32867,2024-05-23,AAPL,170.606324,171.900767,168.220234,169.031925,440209.9,keeep,338.063851
32868,2020-05-08,AAPL,137.925964,140.663476,137.103445,137.479243,507224.7,keeep,274.958486
32869,2024-07-16,AMZN,96.949110,99.434607,94.512888,96.694106,263393.8,keeep,193.388211